Imod6 1068 run tmodel f
Deltares/imod_coupler pull request #158
Opened 2023-04-04 09:04 UTC by HendrikKok

2023-04-05 10:29 UTC, rleander requested changes
Please have another look

2023-04-05 10:29 UTC, rleander commented on imod_coupler/drivers/dfm_metamod/exchange.py
>          condition = np.logical_and(
condition is True when fully realized:
In that case sum_to_dflow>sum_from_dflow when both negative (extraction reported by dflowfm should exceed the extraction requested by the components). But always True when both are positive. Please rename variables to_dflow = requested, from_dflow is realized, also add this line as a comment. The condition is wrong when both are positive (false when sum_to_dflow<sum_from_dflow, but should be true) 
So you could also write:  sum_to_dflow>-abs(sum_from_dflow)

2023-04-05 10:29 UTC, rleander commented on imod_coupler/drivers/dfm_metamod/dfm_wrapper.py
> +        if nr_nodes_1d == 0:
should nr_nodes_2d be unequal to 0 and not nr_nodes_1d ?

2023-04-06 15:43 UTC, luitjansl reviewed
you can make unit tests for the new wrapper functions. In a follow up task, if you want

2023-04-07 12:33 UTC, rleander approved these changes
Review OK

2023-04-07 12:34 UTC, merged