Sw sprinkling ribasim user demands
Deltares/imod_coupler pull request #286
Opened 2024-04-11 15:02 UTC by rleander

2024-04-25 14:14 UTC, HendrikKok requested changes
I would suggest you fix the linter + some comments. Than skip all RibaMetaMod tests and see if all other tests are green. If so, merge to main. We will fix all RibaMetaMod test later.

2024-04-25 14:14 UTC, HendrikKok commented on imod_coupler/drivers/ribametamod/ribametamod.py
> +                    n_priorities = np.size(self.ribasim_user_demand) // n_users
For now, i think we best raise an exception if multiple priorities per MetaSwap user are defined.

2024-04-25 14:14 UTC, HendrikKok commented on imod_coupler/drivers/ribametamod/ribametamod.py
> +        assert "sw_sprinkling" in self.mapping.msw2rib
Perhaps better to move this assert to the mapping initialization, since the mappings itself is static?

2024-04-25 14:14 UTC, HendrikKok commented on imod_coupler/drivers/ribametamod/ribametamod.py
> +        pass
remove the pass :)

2024-04-25 14:14 UTC, HendrikKok commented on imod_coupler/drivers/ribametamod/ribametamod.py
> +        assert "sw_sprinkling" in self.mapping.msw2rib
again, best to move the assert to the mapping method?

2024-04-25 14:14 UTC, HendrikKok commented on imod_coupler/drivers/ribametamod/ribametamod.py
> +        realised_fractions: NDArray[np.float64] = np.full_like(
Do this once at the beginning, now its allocating new arrays on the go...

2024-04-25 14:14 UTC, HendrikKok commented on imod_coupler/drivers/ribametamod/ribametamod.py
> +        self.ribasim_user_realised[:] = 0.0     # reset cummulative for the next timestep
Best to do this at the beginning of the exchange_sprinkling_demand_msw2rib method?

2024-05-14 06:56 UTC, HendrikKok reviewed
Nice work, i have two questions on changes i don't understand

2024-05-14 06:56 UTC, HendrikKok commented on tests/test_imod_coupler/test_ribametamod_cases.py
> +                priority=[3],
why is this?

2024-05-14 06:56 UTC, HendrikKok commented on imod_coupler/drivers/ribametamod/ribametamod.py
> +                self.ribasim_user_realised[:] = (
why is this in now?

2024-05-16 13:15 UTC, HendrikKok commented on imod_coupler/drivers/ribametamod/ribametamod.py
> +                    self.ribasim_user_demand.resize(n_users,n_priorities)
Perhaps add a comment on why this mask is more complicated than for the other 'tradiational' arrays?

2024-05-16 13:15 UTC, HendrikKok commented on imod_coupler/drivers/ribametamod/ribametamod.py
> +                    nprio_per_target = (1-self.mapping.msw2rib['sw_sprinkling_mask']) \
As discussed: Please change the dims used for the sprinkling mapping to nusers instead of nbasins.

2024-05-17 12:31 UTC, HendrikKok approved these changes
All looks fine, except the failing tests in Primod.

2024-05-21 14:55 UTC, merged

2024-05-21 14:56 UTC, rleander commented
Some things still need fixing and investigation, but in this case fixing and extensive testing on main  is preferable